import {
  Layout,
  Table,
  Presentation,
  Calculator,
  BarChart3,
  MessageSquare,
  Image as ImageIcon,
  Mail,
  Code,
  BookOpen,
  TrendingUp,
  Store,
  Brain,
  Wrench,
  Zap,
  Trees,
  Utensils,
  Home,
  Scissors,
  Thermometer,
  HeartPulse,
  Dumbbell,
  Sparkles,
  HardHat,
  Palette,
  Monitor,
  GraduationCap,
  Building2,
  Award,
  Package,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  layout: Layout,
  table: Table,
  presentation: Presentation,
  calculator: Calculator,
  "bar-chart": BarChart3,
  "message-square": MessageSquare,
  image: ImageIcon,
  mail: Mail,
  code: Code,
  "book-open": BookOpen,
  "trending-up": TrendingUp,
  store: Store,
  brain: Brain,
  wrench: Wrench,
  zap: Zap,
  trees: Trees,
  utensils: Utensils,
  home: Home,
  scissors: Scissors,
  thermometer: Thermometer,
  "heart-pulse": HeartPulse,
  dumbbell: Dumbbell,
  sparkles: Sparkles,
  "hard-hat": HardHat,
  palette: Palette,
  monitor: Monitor,
  "graduation-cap": GraduationCap,
  building: Building2,
  award: Award,
};

export function ProductIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = MAP[name] ?? Package;
  return <Icon className={className} strokeWidth={1.6} aria-hidden />;
}
