import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  WorkerDaemonServer, RemoteWorkerAdapter, DistributedWorkerMesh, LiveControlFabric,
  type ExecutionAdapter, type ExecutionStep, type NetworkPolicy, type RuntimeManifest,
  type ControlObjectiveSpec, type ControlTask, type QualityScores
} from "../src/index.js";

const policy:NetworkPolicy={allowedProtocols:["http:"],allowedHosts:["127.0.0.1"],denyPrivateNetworks:false,maxRedirects:0,maxResponseBytes:1_000_000,timeoutMs:5_000};
async function temp(){return mkdtemp(join(tmpdir(),"malachii-rc16-"));}
function manifest(cap="distributed.compute"):RuntimeManifest{return {host:{id:"rc16-test"},capabilities:[{name:cap,evidence:[{id:`obs-${cap}`,kind:"observation",source:"test",authenticity:"verified",directness:"direct",capability:cap,scope:["*"],observedSuccess:true,verifiedAt:new Date(Date.now()-3600000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),revocationChecked:true}]}]};}
function q(v:number):QualityScores{return {accuracy:v,verification:v,completeness:v,intentAlignment:v,executionReadiness:v,structure:v,edgeCases:v};}
function objective():ControlObjectiveSpec{return {id:"obj-distributed-failover",requestedOutcome:"complete through a healthy distributed worker",successCriteria:["remote_result_verified"],constraints:[],riskTier:"T2",qualityFloor:9,requiredCapabilities:["distributed.compute"],allowedDataScopes:["public"],budget:{maxCostIndexPerTask:5,maxLatencyMsPerTask:5000},releasePolicy:{externalPublish:false,requiredHardGates:["truth","worker_identity"]},verification:{minEvidenceReceipts:2,requireIndependentVerification:false},createdAt:new Date(Date.now()-3600000).toISOString()};}
function task(action="act-distributed"):ControlTask{return {id:"task-distributed",actionId:action,title:"distributed compute",capability:"distributed.compute",scope:"public",dataScopes:["public"],impact:"read_only",dependsOn:[],required:true,input:{value:"MALACHII"}};}
function adapter(id:string,mode:"ok"|"fail"="ok"):ExecutionAdapter{return {id,capabilities:["distributed.compute"],async execute(step:ExecutionStep){if(mode==="fail")throw new Error("worker_intentional_failure");const value=String((step.input as any)?.value??"");return {output:{value,workerAdapter:id},evidenceIds:[`compute:${id}:${value}`]};}};}

test("remote worker requires the correct shared observation secret",async()=>{const s=new WorkerDaemonServer({workerId:"auth-worker",secret:"correct",adapters:[adapter("inner")]});const endpoint=await s.start();try{const wrong=new RemoteWorkerAdapter({workerId:"auth-worker",endpoint,secret:"wrong",capabilities:["distributed.compute"],policy});await assert.rejects(()=>wrong.execute({id:"s",actionId:"a",title:"x",capability:"distributed.compute",scope:"public",impact:"read_only",dependsOn:[],required:true,input:{value:"x"}}),/remote_worker_http_500/);}finally{await s.close();}});

test("worker observation promotes only challenged capability to A3 observed",async()=>{const root=await temp();const s=new WorkerDaemonServer({workerId:"observed-worker",secret:"s1",adapters:[adapter("inner")],scopes:["public"],allowedDataScopes:["public"],tags:["research"]});const endpoint=await s.start();try{const live=new LiveControlFabric({stateRoot:join(root,"state"),ledgerPath:join(root,"ledger.jsonl"),getFreshManifest:()=>manifest()});const mesh=new DistributedWorkerMesh(live);const r=await mesh.observeWorker(endpoint,"s1",{policy});assert.equal(r.assurance,"A3_OBSERVED");assert.equal(r.identity?.proof,"observed");assert.equal(r.capabilities.includes("distributed.compute"),true);assert.equal(r.executionAdapterId,"remote.worker.observed-worker");const health=await mesh.heartbeat("observed-worker",policy);assert.equal(health.workerId,"observed-worker");}finally{await s.close();}});

test("revoked remote capability fails closed at the worker boundary",async()=>{const s=new WorkerDaemonServer({workerId:"revoked-worker",secret:"s2",adapters:[adapter("inner")]});const endpoint=await s.start();try{const a=new RemoteWorkerAdapter({workerId:"revoked-worker",endpoint,secret:"s2",capabilities:["distributed.compute"],policy});s.revokeCapability("distributed.compute");await assert.rejects(()=>a.execute({id:"s",actionId:"a",title:"x",capability:"distributed.compute",scope:"public",impact:"read_only",dependsOn:[],required:true,input:{value:"x"}}),/remote_worker_http_500/);}finally{await s.close();}});

test("distributed job adapter records durable lease completion",async()=>{const root=await temp();const s=new WorkerDaemonServer({workerId:"queue-worker",secret:"s3",adapters:[adapter("inner")]});const endpoint=await s.start();try{const live=new LiveControlFabric({stateRoot:join(root,"state"),ledgerPath:join(root,"ledger.jsonl"),getFreshManifest:()=>manifest()});const mesh=new DistributedWorkerMesh(live);await mesh.observeWorker(endpoint,"s3",{policy});const report=await live.run({...objective(),id:"obj-queue"},[task("act-queue")],{evaluateSuccessCriteria:ctx=>({remote_result_verified:ctx.execution.status==="succeeded"}),evaluateQuality:()=>q(9.4),evaluateHardGates:()=>({truth:true,worker_identity:true})});assert.equal(report.status,"completed");const jobs=await live.store.list<any>("queue-worker-queue-worker");assert.equal(jobs.length,1);assert.equal(jobs[0]?.value.status,"succeeded");assert.equal(jobs[0]?.value.attempts,1);}finally{await s.close();}});

test("control plane refreshes routing and fails over to another worker after circuit opens",async()=>{const root=await temp();const bad=new WorkerDaemonServer({workerId:"worker-a",secret:"sa",adapters:[adapter("bad-inner","fail")],tags:["primary"]});const good=new WorkerDaemonServer({workerId:"worker-b",secret:"sb",adapters:[adapter("good-inner","ok")],tags:["secondary"]});const a=await bad.start(),b=await good.start();try{const live=new LiveControlFabric({stateRoot:join(root,"state"),ledgerPath:join(root,"ledger.jsonl"),getFreshManifest:()=>manifest(),healthPolicy:{staleAfterMs:60_000,openCircuitAfterFailures:1,circuitResetAfterMs:60_000}});const mesh=new DistributedWorkerMesh(live);await mesh.observeWorker(a,"sa",{policy,measurements:{quality:10,latencyMs:1,costIndex:0,successRate:1,sampleSize:100}});await mesh.observeWorker(b,"sb",{policy,measurements:{quality:9,latencyMs:5,costIndex:0,successRate:.99,sampleSize:100}});const report=await live.run(objective(),[task()],{evaluateSuccessCriteria:ctx=>({remote_result_verified:ctx.execution.status==="succeeded"}),evaluateQuality:ctx=>q(ctx.execution.status==="succeeded"?9.6:0),evaluateHardGates:ctx=>({truth:ctx.execution.status==="succeeded",worker_identity:true}),repairPlanner:(_o,_observed,recon,next)=>recon.gaps.some((g:{code:string})=>g.code==="execution_not_succeeded")?[task(`act-distributed-repair-${next}`)]:undefined},undefined,1);assert.equal(report.status,"completed");assert.equal(report.rounds.length,2);assert.equal(report.rounds[0]?.routes[0]?.selectedResourceId,"worker-worker-a");assert.equal(report.rounds[1]?.routes[0]?.selectedResourceId,"worker-worker-b");assert.equal(report.finalReconciliation.converged,true);assert.equal(report.finalObserved.qualityFloor,9.6);}finally{await bad.close();await good.close();}});


test("signed heartbeat propagates remote capability revocation into routing state",async()=>{const root=await temp();const s=new WorkerDaemonServer({workerId:"drift-worker",secret:"s4",adapters:[adapter("inner")],scopes:["public"],allowedDataScopes:["public"]});const endpoint=await s.start();try{const live=new LiveControlFabric({stateRoot:join(root,"state"),ledgerPath:join(root,"ledger.jsonl"),getFreshManifest:()=>manifest()});const mesh=new DistributedWorkerMesh(live);await mesh.observeWorker(endpoint,"s4",{policy});s.revokeCapability("distributed.compute");await mesh.heartbeat("drift-worker",policy);const resources=await live.resources();const r=resources.find(x=>x.id==="worker-drift-worker");assert.equal(r?.capabilities.includes("distributed.compute"),false);const report=await live.run({...objective(),id:"obj-drift"},[task("act-drift")],{evaluateSuccessCriteria:()=>({remote_result_verified:true}),evaluateQuality:()=>q(10),evaluateHardGates:()=>({truth:true,worker_identity:true})});assert.equal(report.status,"held");assert.equal(report.rounds[0]?.routes[0]?.reason,"no_eligible_governed_resource");}finally{await s.close();}});
