import test from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdtemp, writeFile, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  AtomicFileStateStore, ContentAddressedStore, PersistentEventLedger, ResourceHealthTable, DurableWorkQueue,
  LocalFilesystemAdapter, LocalCommandAdapter, GovernedHttpAdapter, ChromiumSnapshotAdapter,
  Mcp20260728HttpAdapter, A2A10HttpAdapter,
  OpenAIResponsesAdapter, AnthropicMessagesAdapter, GeminiGenerateContentAdapter,
  LiveControlFabric, ResilientAdapter, FaultInjectionAdapter, JsonlTelemetrySink, hasExecutableCapability,
  assertUrlAllowed, type NetworkPolicy, type SecretProvider,
  type ControlObjectiveSpec, type ControlTask, type ControlResourceDescriptor, type ExecutionAdapter, type ExecutionStep,
  type RuntimeManifest, type QualityScores
} from "../src/index.js";

const localPolicy:NetworkPolicy={allowedProtocols:["http:"],allowedHosts:["127.0.0.1"],denyPrivateNetworks:false,maxRedirects:2,maxResponseBytes:1_000_000,timeoutMs:5_000};

async function temp(){return mkdtemp(join(tmpdir(),"malachii-rc15-"));}
async function server(handler:(req:any,res:any)=>void){
  const s=createServer(handler);await new Promise<void>((resolve,reject)=>{s.once?.("error",reject);s.listen(0,"127.0.0.1",resolve);});
  const a=s.address();const port=typeof a==="object"&&a?Number(a.port):0;
  return {url:`http://127.0.0.1:${port}`,close:()=>new Promise<void>(r=>s.close(()=>r()))};
}
function q(v:number):QualityScores{return {accuracy:v,verification:v,completeness:v,intentAlignment:v,executionReadiness:v,structure:v,edgeCases:v};}
function manifest(cap="web.fetch"):RuntimeManifest{return {host:{id:"test"},capabilities:[{name:cap,evidence:[{id:`e-${cap}`,kind:"observation",source:"test",authenticity:"verified",directness:"direct",capability:cap,scope:["*"],observedSuccess:true,verifiedAt:new Date(Date.now()-3600000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),revocationChecked:true}]}]};}
function objective(cap="web.fetch"):ControlObjectiveSpec{return {id:`obj-${cap.replace(/\W/g,"-")}`,requestedOutcome:"live governed operation",successCriteria:["verified"],constraints:[],riskTier:"T2",qualityFloor:9,requiredCapabilities:[cap],allowedDataScopes:["public"],budget:{maxCostIndexPerTask:5,maxLatencyMsPerTask:5000},releasePolicy:{externalPublish:false,requiredHardGates:["truth"]},verification:{minEvidenceReceipts:1,requireIndependentVerification:false},createdAt:new Date(Date.now()-3600000).toISOString()};}
function task(cap="web.fetch",input:unknown={}):ControlTask{return {id:"t1",actionId:`act-${cap}`,title:"live task",capability:cap,scope:"public",dataScopes:["public"],impact:"read_only",dependsOn:[],required:true,input};}
function resource(id:string,cap:string,adapterId:string):ControlResourceDescriptor{return {id,kind:"execution_plane",provider:"local",capabilities:[cap],scopes:["*"],allowedDataScopes:["public"],tags:["local"],available:true,assurance:"A3_OBSERVED",trustDomain:"TOOL_OUTPUT",measurements:{quality:9.2,latencyMs:20,costIndex:.1,successRate:.99,sampleSize:10},executionAdapterId:adapterId,identity:{subject:`spiffe://malachii.test/${id}`,issuer:"test",proof:"observed",issuedAt:new Date(Date.now()-3600000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()}};}

class MapSecrets implements SecretProvider {constructor(private m:Record<string,string>){} get(n:string){return this.m[n];}}

test("atomic durable state enforces revision and checksum",async()=>{
  const root=await temp();const s=new AtomicFileStateStore(join(root,"state"));
  const a=await s.put("n","x",{v:1});assert.equal(a.revision,1);
  await assert.rejects(()=>s.put("n","x",{v:2},0),/state_revision_conflict/);
  const b=await s.put("n","x",{v:2},1);assert.equal(b.revision,2);assert.deepEqual((await s.get<{v:number}>("n","x"))?.value,{v:2});
});

test("content addressed store deduplicates by hash",async()=>{const root=await temp();const c=new ContentAddressedStore(join(root,"cas"));const a=await c.put("same");const b=await c.put("same");assert.equal(a.hash,b.hash);assert.equal(new TextDecoder().decode(await c.get(a.hash)),"same");});

test("persistent ledger survives restart with chain intact",async()=>{const root=await temp();const path=join(root,"ledger.jsonl");const a=new PersistentEventLedger(path);a.append("x",{a:1},new Date("2026-08-15T20:00:00Z"));const rootHash=a.rootHash();const b=new PersistentEventLedger(path);assert.equal(b.verify(),true);assert.equal(b.rootHash(),rootHash);b.append("y",{b:2},new Date("2026-08-15T20:00:01Z"));assert.equal(b.snapshot().length,2);});

test("resource health opens circuit and later half-opens",()=>{let now=new Date("2026-08-15T20:00:00Z");const h=new ResourceHealthTable({staleAfterMs:60_000,openCircuitAfterFailures:2,circuitResetAfterMs:1_000});h.heartbeat("r",now);h.recordFailure("r","x",now);h.recordFailure("r","x",now);assert.equal(h.isHealthy("r",now),false);now=new Date(now.getTime()+1500);assert.equal(h.get("r",now)?.circuit,"half_open");assert.equal(h.isHealthy("r",now),true);});

test("durable queue leases and completes exactly by lease owner",async()=>{const root=await temp();const s=new AtomicFileStateStore(join(root,"state"));const qx=new DurableWorkQueue<{x:number},{ok:boolean}>(s,"jobs");const j=await qx.enqueue({x:1});const c=await qx.claim("w1",1000);assert.equal(c?.id,j.id);await assert.rejects(()=>qx.complete(j.id,"w2",{ok:true}),/job_lease_owner_mismatch/);await qx.complete(j.id,"w1",{ok:true});const e=await s.get<any>("queue-jobs",j.id);assert.equal(e?.value.status,"succeeded");});

test("filesystem adapter is rooted and blocks traversal",async()=>{const root=await temp();await writeFile(join(root,"a.txt"),"hello");const fsA=new LocalFilesystemAdapter({root,allowWrite:true});const r=await fsA.execute({id:"s",actionId:"a",title:"r",capability:"fs.read",scope:"local",impact:"read_only",dependsOn:[],required:true,input:{path:"a.txt"}});assert.equal(r.output,"hello");await assert.rejects(()=>fsA.execute({id:"s2",actionId:"a2",title:"x",capability:"fs.read",scope:"local",impact:"read_only",dependsOn:[],required:true,input:{path:"../escape"}}),/filesystem_path_escape/);});

test("command adapter uses argv not shell and enforces allowlist",async()=>{const root=await temp();const a=new LocalCommandAdapter({root,allowedCommands:["node"]});const r=await a.execute({id:"s",actionId:"a",title:"node",capability:"command.execute",scope:"local",impact:"read_only",dependsOn:[],required:true,input:{command:"node",args:["-e","process.stdout.write('OK')"]}});assert.equal((r.output as any).stdout,"OK");await assert.rejects(()=>a.execute({id:"s2",actionId:"a2",title:"bash",capability:"command.execute",scope:"local",impact:"read_only",dependsOn:[],required:true,input:{command:"bash",args:["-c","echo bad"]}}),/command_not_allowlisted/);});

test("network policy denies private targets under public policy",async()=>{await assert.rejects(()=>assertUrlAllowed("https://127.0.0.1/",{...localPolicy,allowedProtocols:["https:"],denyPrivateNetworks:true}),/network_private_address_denied/);});

test("governed HTTP adapter performs bounded live request",async()=>{const s=await server((req,res)=>{res.writeHead(200,{"content-type":"text/plain"});res.end("hello-live");});try{const a=new GovernedHttpAdapter({policy:localPolicy});const r=await a.execute({id:"s",actionId:"a",title:"fetch",capability:"web.fetch",scope:"public",impact:"read_only",dependsOn:[],required:true,input:{url:`${s.url}/x`}});assert.equal((r.output as any).body,"hello-live");assert.ok((r.evidenceIds??[]).length===1);}finally{await s.close();}});

test("MCP 2026-07-28 adapter sends stateless routing headers",async()=>{let seen:any={};const s=await server(async(req,res)=>{let body="";for await(const c of req)body+=String(c);seen={method:req.headers["mcp-method"],name:req.headers["mcp-name"],version:req.headers["mcp-protocol-version"],body:JSON.parse(body)};res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({jsonrpc:"2.0",id:seen.body.id,result:{content:[{type:"text",text:"ok"}]}}));});try{const a=new Mcp20260728HttpAdapter({endpoint:`${s.url}/mcp`,policy:localPolicy});const r=await a.execute({id:"s",actionId:"a",title:"mcp",capability:"mcp.invoke",scope:"public",impact:"read_only",dependsOn:[],required:true,input:{toolName:"search",arguments:{q:"x"}}});assert.equal(seen.method,"tools/call");assert.equal(seen.name,"search");assert.equal(seen.version,"2026-07-28");assert.equal(seen.body.method,"tools/call");assert.ok((r.evidenceIds??[])[0]?.startsWith("mcp:"));}finally{await s.close();}});

test("A2A 1.0 adapter discovers card and sends REST message",async()=>{const s=await server(async(req,res)=>{if(req.url==="/.well-known/agent-card.json"){res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({name:"Researcher",description:"research",version:"1",supportedInterfaces:[{url:s.url,protocolBinding:"HTTP+JSON",protocolVersion:"1.0"}],capabilities:{},skills:[{id:"research",name:"Research",description:"research",tags:["research"]}],signatures:[{protected:"x",signature:"y"}]}));return;}if(req.url==="/message:send"){let body="";for await(const c of req)body+=String(c);const j=JSON.parse(body);res.writeHead(200,{"content-type":"application/a2a+json"});res.end(JSON.stringify({message:{role:"ROLE_AGENT",parts:[{text:`ack:${j.message.parts[0].text}`}]}}));return;}res.writeHead(404);res.end();});try{const a=new A2A10HttpAdapter({baseUrl:s.url,policy:localPolicy});const card=await a.discover();assert.equal(card.name,"Researcher");const discovered=await a.discoveredResources();assert.equal(discovered[0]?.assurance,"A2_AUTHENTICATED_DECLARATION");const r=await a.execute({id:"s",actionId:"a",title:"delegate",capability:"a2a.delegate",scope:"public",impact:"read_only",dependsOn:[],required:true,input:{prompt:"hello"}});assert.ok(JSON.stringify(r.output).includes("ack:hello"));}finally{await s.close();}});

test("provider adapters can operate through governed HTTP without storing secrets",async()=>{const got:string[]=[];const s=await server(async(req,res)=>{let body="";for await(const c of req)body+=String(c);got.push(`${req.url}|${req.headers.authorization??req.headers["x-api-key"]??req.headers["x-goog-api-key"]}`);res.writeHead(200,{"content-type":"application/json"});if(req.url==="/openai")res.end(JSON.stringify({output_text:"openai-ok"}));else if(req.url==="/anthropic")res.end(JSON.stringify({content:[{type:"text",text:"anthropic-ok"}]}));else res.end(JSON.stringify({candidates:[{content:{parts:[{text:"gemini-ok"}]}}]}));});try{const secrets=new MapSecrets({OPENAI_API_KEY:"oa-secret",ANTHROPIC_API_KEY:"an-secret",GEMINI_API_KEY:"gm-secret"});const step=(model:string):ExecutionStep=>({id:model,actionId:`a-${model}`,title:model,capability:"model.generate",scope:"public",impact:"read_only",dependsOn:[],required:true,input:{prompt:"hi",model}});const oa=await new OpenAIResponsesAdapter(secrets,{baseUrl:`${s.url}/openai`,policy:localPolicy}).execute(step("gpt-test"));const an=await new AnthropicMessagesAdapter(secrets,{baseUrl:`${s.url}/anthropic`,policy:localPolicy}).execute(step("claude-test"));const gm=await new GeminiGenerateContentAdapter(secrets,{baseUrl:`${s.url}`,policy:localPolicy}).execute(step("gemini-test"));assert.equal((oa.output as any).text,"openai-ok");assert.equal((an.output as any).text,"anthropic-ok");assert.equal((gm.output as any).text,"gemini-ok");assert.ok(got.some(x=>x.includes("oa-secret")));assert.ok(got.some(x=>x.includes("an-secret")));assert.ok(got.some(x=>x.includes("gm-secret")));}finally{await s.close();}});

test("resilient adapter retries read-only but not external side effects",async()=>{let calls=0;const inner:ExecutionAdapter={id:"x",capabilities:["x"],async execute(){calls++;if(calls===1)throw new Error("transient");return {evidenceIds:["ok"]};}};const r=new ResilientAdapter(inner,{retries:1,retryDelayMs:1,timeoutMs:1000,retryImpacts:["read_only"]});await r.execute({id:"s",actionId:"a",title:"x",capability:"x",scope:"x",impact:"read_only",dependsOn:[],required:true});assert.equal(calls,2);calls=0;await assert.rejects(()=>r.execute({id:"s2",actionId:"a2",title:"x",capability:"x",scope:"x",impact:"external_side_effect",dependsOn:[],required:true}),/transient/);assert.equal(calls,1);});

test("fault injection exposes failure instead of hiding it",async()=>{const inner:ExecutionAdapter={id:"x",capabilities:["x"],async execute(){return {evidenceIds:["ok"]};}};const f=new FaultInjectionAdapter(inner,2);await f.execute({id:"1",actionId:"1",title:"x",capability:"x",scope:"x",impact:"read_only",dependsOn:[],required:true});await assert.rejects(()=>f.execute({id:"2",actionId:"2",title:"x",capability:"x",scope:"x",impact:"read_only",dependsOn:[],required:true}),/fault_injected/);});

test("live control fabric persists objective observed state report and ledger",async()=>{const root=await temp();const s=await server((req,res)=>{res.writeHead(200,{"content-type":"text/plain"});res.end("verified-live");});try{const adapter=new GovernedHttpAdapter({id:"http-live",policy:localPolicy});const fabric=new LiveControlFabric({stateRoot:join(root,"state"),ledgerPath:join(root,"ledger.jsonl"),getFreshManifest:()=>manifest("web.fetch")});await fabric.registerResource(resource("web1","web.fetch",adapter.id),adapter);const report=await fabric.run(objective("web.fetch"),[task("web.fetch",{url:s.url})],{evaluateSuccessCriteria:()=>({verified:true}),evaluateQuality:()=>q(9.5),evaluateHardGates:()=>({truth:true})});assert.equal(report.status,"completed");const stored=await fabric.store.get<any>("reports",objective("web.fetch").id);assert.equal(stored?.value.status,"completed");const restarted=new PersistentEventLedger(join(root,"ledger.jsonl"));assert.equal(restarted.verify(),true);assert.ok(restarted.snapshot().some(e=>e.type==="fabric.objective.checkpointed"));}finally{await s.close();}});

test("chromium snapshot adapter is local-only input and rejects missing html",async()=>{const root=await temp();const a=new ChromiumSnapshotAdapter({root,allowNoSandbox:true});await assert.rejects(()=>a.execute({id:"s",actionId:"a",title:"b",capability:"browser.render_snapshot",scope:"local",impact:"read_only",dependsOn:[],required:true,input:{}}),/browser_snapshot_html_required/);});


test("runtime manifest wildcard scope is honored consistently",()=>{assert.equal(hasExecutableCapability(manifest("web.fetch"),"web.fetch","public.deep",new Date("2026-08-16T00:00:00Z")),true);});

test("open resource circuit removes worker from next routing snapshot",async()=>{const root=await temp();const adapter:ExecutionAdapter={id:"unstable",capabilities:["web.fetch"],async execute(){return {evidenceIds:["x"]};}};const fabric=new LiveControlFabric({stateRoot:join(root,"state"),ledgerPath:join(root,"ledger.jsonl"),getFreshManifest:()=>manifest("web.fetch"),healthPolicy:{staleAfterMs:60000,openCircuitAfterFailures:2,circuitResetAfterMs:60000}});await fabric.registerResource(resource("r","web.fetch",adapter.id),adapter);fabric.health.recordFailure("r","x");fabric.health.recordFailure("r","x");const report=await fabric.run(objective("web.fetch"),[task("web.fetch",{})],{evaluateSuccessCriteria:()=>({verified:true}),evaluateQuality:()=>q(10),evaluateHardGates:()=>({truth:true})});assert.equal(report.status,"held");assert.equal(report.rounds[0]?.routes[0]?.reason,"no_eligible_governed_resource");});

test("JSONL telemetry redacts secret-like attributes",async()=>{const root=await temp();const p=join(root,"telemetry.jsonl");const t=new JsonlTelemetrySink(p);t.emit({name:"x",timestamp:"2026-08-16T00:00:00Z",attributes:{"malachii.objective.id":"o","authorization":"Bearer secret","api_key":"abc"}});const raw=String(await readFile(p,{encoding:"utf8"}));assert.ok(!raw.includes("Bearer secret"));assert.ok(!raw.includes('"abc"'));assert.ok(raw.includes("[REDACTED]"));});
